def addFailure(self, test, err):
    super(FbJsonTestResult, self).addFailure(test, err)
    self.setException(test, TestStatus.FAILED, err)
