{
  LOG.warn(t,"Build error caused by exception");
  t.printStackTrace(stdErr);
  printBuildFailureInternal("Unexpected internal error (if you are using buckd, you should restart it).");
}
