{
  try {
    result=callable.call();
  }
 catch (  Exception e) {
    callableException=e;
  }
 finally {
synchronized (lock) {
      hasRun=true;
      lock.notifyAll();
    }
  }
}
