def error(self, message):
    'error(message: string)\n\n        Prints a usage message incorporating the message to stderr and\n        exits.\n\n        If you override this in a subclass, it should not return -- it\n        should either exit or raise an exception.\n        '
    self.print_usage(_sys.stderr)
    self.exit(2, (_('%s: error: %s\n') % (self.prog, message)))
