def addError(self, test, err):
    super(FbJsonTestResult, self).addError(test, err)
    self.setException(test, TestStatus.ABORTED, err)
