{
  ExecutionContext context=TestExecutionContext.newInstance();
  DefaultStepRunner runner=new DefaultStepRunner(context,MoreExecutors.newDirectExecutorService());
  try {
    runner.runStep(new ExplosionStep());
    fail("Should have thrown a StepFailedException!");
  }
 catch (  StepFailedException e) {
    assertTrue(e.getMessage().startsWith("Failed on step explode with an exception:\n#yolo"));
  }
}
