def addExpectedFailure(self, test, err):
    super(BuckTestResult, self).addExpectedFailure(test, err)
    self.setException(test, TestStatus.EXPECTED_FAILURE, err)
